name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.2.0'
      - name: Install deps
        # this runs a build script so there is no dedicated build
        run: |
          npm i -g yarn 
          yarn install
      - name: Run lint
        run: yarn lint
      - name: Run typecheck
        run: yarn test:ts
      - name: Run tests
        run: yarn test
